//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace ES2.XSD.PopulationStateDefinition_SCHEMA {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_SystemInfluenceState))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_HeroAssignedOnSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_SystemBesieged))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_SystemBlockaded))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_StarSystemImprovement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_AcademyColonized))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_DiplomaticAbility))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_HappinessStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatatableElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_SystemInfluenceState))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_HeroAssignedOnSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_SystemBesieged))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_SystemBlockaded))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_StarSystemImprovement))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_AcademyColonized))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_DiplomaticAbility))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PopulationStateDefinition_HappinessStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class PopulationStateDefinition : DatatableElement {
        
        private string eventNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
                this.RaisePropertyChanged("EventName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class PopulationStateDefinition_HappinessStatus : PopulationStateDefinition {
        
        private HappinessProviderLocation happinessProviderLocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public HappinessProviderLocation HappinessProviderLocation {
            get {
                return this.happinessProviderLocationField;
            }
            set {
                this.happinessProviderLocationField = value;
                this.RaisePropertyChanged("HappinessProviderLocation");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum HappinessProviderLocation {
        
        /// <remarks/>
        Empire,
        
        /// <remarks/>
        Context,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class PopulationStateDefinition_DiplomaticAbility : PopulationStateDefinition {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class PopulationStateDefinition_AcademyColonized : PopulationStateDefinition {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class PopulationStateDefinition_StarSystemImprovement : PopulationStateDefinition {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class PopulationStateDefinition_SystemBlockaded : PopulationStateDefinition {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class PopulationStateDefinition_SystemBesieged : PopulationStateDefinition {
        
        private string descriptorNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DescriptorName {
            get {
                return this.descriptorNameField;
            }
            set {
                this.descriptorNameField = value;
                this.RaisePropertyChanged("DescriptorName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class PopulationStateDefinition_HeroAssignedOnSystem : PopulationStateDefinition {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class PopulationStateDefinition_SystemInfluenceState : PopulationStateDefinition {
    }
}
