//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace ES2.XSD.RealizationEventDefinition_SCHEMA {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RealizationEventDefinition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatatableElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RealizationEventWeightChangeDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int weightChangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int WeightChange {
            get {
                return this.weightChangeField;
            }
            set {
                this.weightChangeField = value;
                this.RaisePropertyChanged("WeightChange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class RealizationEventDefinition : DatatableElement {
        
        private EncounterEntityType[] availableInitiatorTypeField;
        
        private EncounterEntityType[] availableTargetTypeField;
        
        private RealizationEventWeightChangeDefinition[] realizationEventWeightChangeField;
        
        private int defaultWeightField;
        
        private bool ignoredByDirectorField;
        
        public RealizationEventDefinition() {
            this.defaultWeightField = 0;
            this.ignoredByDirectorField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AvailableInitiatorType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EncounterEntityType[] AvailableInitiatorType {
            get {
                return this.availableInitiatorTypeField;
            }
            set {
                this.availableInitiatorTypeField = value;
                this.RaisePropertyChanged("AvailableInitiatorType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AvailableTargetType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EncounterEntityType[] AvailableTargetType {
            get {
                return this.availableTargetTypeField;
            }
            set {
                this.availableTargetTypeField = value;
                this.RaisePropertyChanged("AvailableTargetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RealizationEventWeightChange", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RealizationEventWeightChangeDefinition[] RealizationEventWeightChange {
            get {
                return this.realizationEventWeightChangeField;
            }
            set {
                this.realizationEventWeightChangeField = value;
                this.RaisePropertyChanged("RealizationEventWeightChange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int DefaultWeight {
            get {
                return this.defaultWeightField;
            }
            set {
                this.defaultWeightField = value;
                this.RaisePropertyChanged("DefaultWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IgnoredByDirector {
            get {
                return this.ignoredByDirectorField;
            }
            set {
                this.ignoredByDirectorField = value;
                this.RaisePropertyChanged("IgnoredByDirector");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum EncounterEntityType {
        
        /// <remarks/>
        Arena,
        
        /// <remarks/>
        EffectArea,
        
        /// <remarks/>
        Group,
        
        /// <remarks/>
        Flotilla,
        
        /// <remarks/>
        Ship,
        
        /// <remarks/>
        ShipSection,
        
        /// <remarks/>
        Module,
        
        /// <remarks/>
        Salvo,
        
        /// <remarks/>
        Undefined,
    }
}
