//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FleetMissionDefinition))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DatatableElement : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class FleetMissionDefinition : DatatableElement {
    
    private string behaviorTreeField;
    
    private string actionLevelField;
    
    private float roamDistanceField;
    
    private int minimumInvasionTurnField;
    
    private bool canRoamOutsideConstellationField;
    
    public FleetMissionDefinition() {
        this.roamDistanceField = ((float)(0F));
        this.minimumInvasionTurnField = 0;
        this.canRoamOutsideConstellationField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BehaviorTree {
        get {
            return this.behaviorTreeField;
        }
        set {
            this.behaviorTreeField = value;
            this.RaisePropertyChanged("BehaviorTree");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ActionLevel {
        get {
            return this.actionLevelField;
        }
        set {
            this.actionLevelField = value;
            this.RaisePropertyChanged("ActionLevel");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float RoamDistance {
        get {
            return this.roamDistanceField;
        }
        set {
            this.roamDistanceField = value;
            this.RaisePropertyChanged("RoamDistance");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int MinimumInvasionTurn {
        get {
            return this.minimumInvasionTurnField;
        }
        set {
            this.minimumInvasionTurnField = value;
            this.RaisePropertyChanged("MinimumInvasionTurn");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool CanRoamOutsideConstellation {
        get {
            return this.canRoamOutsideConstellationField;
        }
        set {
            this.canRoamOutsideConstellationField = value;
            this.RaisePropertyChanged("CanRoamOutsideConstellation");
        }
    }
}
