//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GroundBattleTroopTypeConfig))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DatatableElement : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class GroundBattleTroopTypeConfig : DatatableElement {
    
    private float spawnXPositionOffsetField;
    
    private float spawnMinZPositionOffsetField;
    
    private float spawnMaxZPositionOffsetField;
    
    private float attackAdditionalDelayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float SpawnXPositionOffset {
        get {
            return this.spawnXPositionOffsetField;
        }
        set {
            this.spawnXPositionOffsetField = value;
            this.RaisePropertyChanged("SpawnXPositionOffset");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float SpawnMinZPositionOffset {
        get {
            return this.spawnMinZPositionOffsetField;
        }
        set {
            this.spawnMinZPositionOffsetField = value;
            this.RaisePropertyChanged("SpawnMinZPositionOffset");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float SpawnMaxZPositionOffset {
        get {
            return this.spawnMaxZPositionOffsetField;
        }
        set {
            this.spawnMaxZPositionOffsetField = value;
            this.RaisePropertyChanged("SpawnMaxZPositionOffset");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float AttackAdditionalDelay {
        get {
            return this.attackAdditionalDelayField;
        }
        set {
            this.attackAdditionalDelayField = value;
            this.RaisePropertyChanged("AttackAdditionalDelay");
        }
    }
}
