//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GroundBattleViewerConfig))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DatatableElement : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class GroundBattleViewerConfig : DatatableElement {
    
    private float spawnZoneXMinField;
    
    private float spawnZoneXMaxField;
    
    private float spawnZoneZMinField;
    
    private float spawnZoneZMaxField;
    
    private float firstApproachPhaseDelayField;
    
    private float firstApproachPhaseDurationField;
    
    private float roundApproachPhaseDurationField;
    
    private float bombardmentExplosionDelayMinField;
    
    private float bombardmentExplosionDelayMaxField;
    
    private float bombardmentTargetDelayMinField;
    
    private float bombardmentTargetDelayMaxField;
    
    private float bombardmentZoneXMinField;
    
    private float bombardmentZoneXMaxField;
    
    private float firstAttackPhaseDelayField;
    
    private float attackPhaseDurationField;
    
    private float attackZoneXMinField;
    
    private float attackZoneXMaxField;
    
    private float nextRoundDelayField;
    
    private float exitBattleDelayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float SpawnZoneXMin {
        get {
            return this.spawnZoneXMinField;
        }
        set {
            this.spawnZoneXMinField = value;
            this.RaisePropertyChanged("SpawnZoneXMin");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float SpawnZoneXMax {
        get {
            return this.spawnZoneXMaxField;
        }
        set {
            this.spawnZoneXMaxField = value;
            this.RaisePropertyChanged("SpawnZoneXMax");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float SpawnZoneZMin {
        get {
            return this.spawnZoneZMinField;
        }
        set {
            this.spawnZoneZMinField = value;
            this.RaisePropertyChanged("SpawnZoneZMin");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float SpawnZoneZMax {
        get {
            return this.spawnZoneZMaxField;
        }
        set {
            this.spawnZoneZMaxField = value;
            this.RaisePropertyChanged("SpawnZoneZMax");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float FirstApproachPhaseDelay {
        get {
            return this.firstApproachPhaseDelayField;
        }
        set {
            this.firstApproachPhaseDelayField = value;
            this.RaisePropertyChanged("FirstApproachPhaseDelay");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float FirstApproachPhaseDuration {
        get {
            return this.firstApproachPhaseDurationField;
        }
        set {
            this.firstApproachPhaseDurationField = value;
            this.RaisePropertyChanged("FirstApproachPhaseDuration");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float RoundApproachPhaseDuration {
        get {
            return this.roundApproachPhaseDurationField;
        }
        set {
            this.roundApproachPhaseDurationField = value;
            this.RaisePropertyChanged("RoundApproachPhaseDuration");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float BombardmentExplosionDelayMin {
        get {
            return this.bombardmentExplosionDelayMinField;
        }
        set {
            this.bombardmentExplosionDelayMinField = value;
            this.RaisePropertyChanged("BombardmentExplosionDelayMin");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float BombardmentExplosionDelayMax {
        get {
            return this.bombardmentExplosionDelayMaxField;
        }
        set {
            this.bombardmentExplosionDelayMaxField = value;
            this.RaisePropertyChanged("BombardmentExplosionDelayMax");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float BombardmentTargetDelayMin {
        get {
            return this.bombardmentTargetDelayMinField;
        }
        set {
            this.bombardmentTargetDelayMinField = value;
            this.RaisePropertyChanged("BombardmentTargetDelayMin");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float BombardmentTargetDelayMax {
        get {
            return this.bombardmentTargetDelayMaxField;
        }
        set {
            this.bombardmentTargetDelayMaxField = value;
            this.RaisePropertyChanged("BombardmentTargetDelayMax");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float BombardmentZoneXMin {
        get {
            return this.bombardmentZoneXMinField;
        }
        set {
            this.bombardmentZoneXMinField = value;
            this.RaisePropertyChanged("BombardmentZoneXMin");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float BombardmentZoneXMax {
        get {
            return this.bombardmentZoneXMaxField;
        }
        set {
            this.bombardmentZoneXMaxField = value;
            this.RaisePropertyChanged("BombardmentZoneXMax");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float FirstAttackPhaseDelay {
        get {
            return this.firstAttackPhaseDelayField;
        }
        set {
            this.firstAttackPhaseDelayField = value;
            this.RaisePropertyChanged("FirstAttackPhaseDelay");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float AttackPhaseDuration {
        get {
            return this.attackPhaseDurationField;
        }
        set {
            this.attackPhaseDurationField = value;
            this.RaisePropertyChanged("AttackPhaseDuration");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float AttackZoneXMin {
        get {
            return this.attackZoneXMinField;
        }
        set {
            this.attackZoneXMinField = value;
            this.RaisePropertyChanged("AttackZoneXMin");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float AttackZoneXMax {
        get {
            return this.attackZoneXMaxField;
        }
        set {
            this.attackZoneXMaxField = value;
            this.RaisePropertyChanged("AttackZoneXMax");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float NextRoundDelay {
        get {
            return this.nextRoundDelayField;
        }
        set {
            this.nextRoundDelayField = value;
            this.RaisePropertyChanged("NextRoundDelay");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float ExitBattleDelay {
        get {
            return this.exitBattleDelayField;
        }
        set {
            this.exitBattleDelayField = value;
            this.RaisePropertyChanged("ExitBattleDelay");
        }
    }
}
