//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlAttributeOverride : object, System.ComponentModel.INotifyPropertyChanged
{

	private XmlExtraType[] extraTypeField;

	private string nameField;

	private string dataTypeField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("ExtraType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public XmlExtraType[] ExtraType
	{
		get
		{
			return this.extraTypeField;
		}
		set
		{
			this.extraTypeField = value;
			this.RaisePropertyChanged("ExtraType");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
			this.RaisePropertyChanged("Name");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string DataType
	{
		get
		{
			return this.dataTypeField;
		}
		set
		{
			this.dataTypeField = value;
			this.RaisePropertyChanged("DataType");
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class XmlExtraType : object, System.ComponentModel.INotifyPropertyChanged
{

	private string nameField;

	private string dataTypeField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
			this.RaisePropertyChanged("Name");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string DataType
	{
		get
		{
			return this.dataTypeField;
		}
		set
		{
			this.dataTypeField = value;
			this.RaisePropertyChanged("DataType");
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AIPlugin))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DatabasePlugin))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LocalizationPlugin))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistryPlugin))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RuntimePlugin : object, System.ComponentModel.INotifyPropertyChanged
{

	private int priorityField;

	public RuntimePlugin()
	{
		this.priorityField = 0;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	[System.ComponentModel.DefaultValueAttribute(0)]
	public int Priority
	{
		get
		{
			return this.priorityField;
		}
		set
		{
			this.priorityField = value;
			this.RaisePropertyChanged("Priority");
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AIPlugin : RuntimePlugin
{

	private string[] assemblyPathField;

	private Configuration configurationField;

	public AIPlugin()
	{
		this.configurationField = Configuration.Release;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("AssemblyPath", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string[] AssemblyPath
	{
		get
		{
			return this.assemblyPathField;
		}
		set
		{
			this.assemblyPathField = value;
			this.RaisePropertyChanged("AssemblyPath");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	[System.ComponentModel.DefaultValueAttribute(Configuration.Release)]
	public Configuration Configuration
	{
		get
		{
			return this.configurationField;
		}
		set
		{
			this.configurationField = value;
			this.RaisePropertyChanged("Configuration");
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
public enum Configuration
{

	/// <remarks/>
	Release,

	/// <remarks/>
	Debug,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DatabasePlugin : RuntimePlugin
{

	private XmlExtraType[] extraTypesField;

	private string[] filePathField;

	private XmlAttributeOverride[] overridesField;

	private string dataTypeField;

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	[System.Xml.Serialization.XmlArrayItemAttribute("ExtraType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
	public XmlExtraType[] ExtraTypes
	{
		get
		{
			return this.extraTypesField;
		}
		set
		{
			this.extraTypesField = value;
			this.RaisePropertyChanged("ExtraTypes");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("FilePath", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string[] FilePath
	{
		get
		{
			return this.filePathField;
		}
		set
		{
			this.filePathField = value;
			this.RaisePropertyChanged("FilePath");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	[System.Xml.Serialization.XmlArrayItemAttribute("Override", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
	public XmlAttributeOverride[] Overrides
	{
		get
		{
			return this.overridesField;
		}
		set
		{
			this.overridesField = value;
			this.RaisePropertyChanged("Overrides");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string DataType
	{
		get
		{
			return this.dataTypeField;
		}
		set
		{
			this.dataTypeField = value;
			this.RaisePropertyChanged("DataType");
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LocalizationPlugin : RuntimePlugin
{

	private string[] directoryField;

	private string defaultLanguageField;

	public LocalizationPlugin()
	{
		this.defaultLanguageField = "english";
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("Directory", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string[] Directory
	{
		get
		{
			return this.directoryField;
		}
		set
		{
			this.directoryField = value;
			this.RaisePropertyChanged("Directory");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	[System.ComponentModel.DefaultValueAttribute("english")]
	public string DefaultLanguage
	{
		get
		{
			return this.defaultLanguageField;
		}
		set
		{
			this.defaultLanguageField = value;
			this.RaisePropertyChanged("DefaultLanguage");
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RegistryPlugin : RuntimePlugin
{

	private string[] filePathField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("FilePath", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string[] FilePath
	{
		get
		{
			return this.filePathField;
		}
		set
		{
			this.filePathField = value;
			this.RaisePropertyChanged("FilePath");
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Tags : object, System.ComponentModel.INotifyPropertyChanged
{

	private string valueField;

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
			this.RaisePropertyChanged("Value");
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
public partial class RuntimeModule : object, System.ComponentModel.INotifyPropertyChanged
{

	private string titleField;

	private string descriptionField;

	private string[] authorField;

	private string homepageField;

	private string previewImageFileField;

	private string releaseNotesField;

	private Tags tagsField;

	private string[] thumbnailField;

	private RuntimePlugin[] pluginsField;

	private RuntimeModuleType typeField;

	private string versionField;

	private string nameField;

	public RuntimeModule()
	{
		this.versionField = "1.0";
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Title
	{
		get
		{
			return this.titleField;
		}
		set
		{
			this.titleField = value;
			this.RaisePropertyChanged("Title");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Description
	{
		get
		{
			return this.descriptionField;
		}
		set
		{
			this.descriptionField = value;
			this.RaisePropertyChanged("Description");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("Author", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string[] Author
	{
		get
		{
			return this.authorField;
		}
		set
		{
			this.authorField = value;
			this.RaisePropertyChanged("Author");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string Homepage
	{
		get
		{
			return this.homepageField;
		}
		set
		{
			this.homepageField = value;
			this.RaisePropertyChanged("Homepage");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string PreviewImageFile
	{
		get
		{
			return this.previewImageFileField;
		}
		set
		{
			this.previewImageFileField = value;
			this.RaisePropertyChanged("PreviewImageFile");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string ReleaseNotes
	{
		get
		{
			return this.releaseNotesField;
		}
		set
		{
			this.releaseNotesField = value;
			this.RaisePropertyChanged("ReleaseNotes");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public Tags Tags
	{
		get
		{
			return this.tagsField;
		}
		set
		{
			this.tagsField = value;
			this.RaisePropertyChanged("Tags");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("Thumbnail", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	public string[] Thumbnail
	{
		get
		{
			return this.thumbnailField;
		}
		set
		{
			this.thumbnailField = value;
			this.RaisePropertyChanged("Thumbnail");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
	[System.Xml.Serialization.XmlArrayItemAttribute(typeof(AIPlugin), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
	[System.Xml.Serialization.XmlArrayItemAttribute(typeof(DatabasePlugin), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
	[System.Xml.Serialization.XmlArrayItemAttribute(typeof(LocalizationPlugin), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
	[System.Xml.Serialization.XmlArrayItemAttribute(typeof(RegistryPlugin), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
	public RuntimePlugin[] Plugins
	{
		get
		{
			return this.pluginsField;
		}
		set
		{
			this.pluginsField = value;
			this.RaisePropertyChanged("Plugins");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public RuntimeModuleType Type
	{
		get
		{
			return this.typeField;
		}
		set
		{
			this.typeField = value;
			this.RaisePropertyChanged("Type");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	[System.ComponentModel.DefaultValueAttribute("1.0")]
	public string Version
	{
		get
		{
			return this.versionField;
		}
		set
		{
			this.versionField = value;
			this.RaisePropertyChanged("Version");
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
			this.RaisePropertyChanged("Name");
		}
	}

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	protected void RaisePropertyChanged(string propertyName)
	{
		System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		if ((propertyChanged != null))
		{
			propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
public enum RuntimeModuleType
{

	/// <remarks/>
	Standalone,

	/// <remarks/>
	Conversion,

	/// <remarks/>
	Extension,
}
