//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PropertyFilter : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string propertyNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PropertyName {
        get {
            return this.propertyNameField;
        }
        set {
            this.propertyNameField = value;
            this.RaisePropertyChanged("PropertyName");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GuiPanelFeatureDescription : object, System.ComponentModel.INotifyPropertyChanged {
    
    private PropertyFilter[] propertyFiltersField;
    
    private string prefabField;
    
    private bool hideInCompactModeField;
    
    private bool doNotHandleCompactModeField;
    
    private bool showImageField;
    
    public GuiPanelFeatureDescription() {
        this.hideInCompactModeField = false;
        this.doNotHandleCompactModeField = false;
        this.showImageField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public PropertyFilter[] PropertyFilters {
        get {
            return this.propertyFiltersField;
        }
        set {
            this.propertyFiltersField = value;
            this.RaisePropertyChanged("PropertyFilters");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Prefab {
        get {
            return this.prefabField;
        }
        set {
            this.prefabField = value;
            this.RaisePropertyChanged("Prefab");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool HideInCompactMode {
        get {
            return this.hideInCompactModeField;
        }
        set {
            this.hideInCompactModeField = value;
            this.RaisePropertyChanged("HideInCompactMode");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool DoNotHandleCompactMode {
        get {
            return this.doNotHandleCompactModeField;
        }
        set {
            this.doNotHandleCompactModeField = value;
            this.RaisePropertyChanged("DoNotHandleCompactMode");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool ShowImage {
        get {
            return this.showImageField;
        }
        set {
            this.showImageField = value;
            this.RaisePropertyChanged("ShowImage");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Offset : object, System.ComponentModel.INotifyPropertyChanged {
    
    private float xField;
    
    private float yField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
            this.RaisePropertyChanged("X");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
            this.RaisePropertyChanged("Y");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class GuiTooltipDescription : object, System.ComponentModel.INotifyPropertyChanged {
    
    private Offset freeOffsetField;
    
    private Offset anchorOffsetField;
    
    private GuiPanelFeatureDescription[] panelFeatureDescriptionField;
    
    private float priorityField;
    
    private string tooltipPrefabField;
    
    private string tooltipWindowField;
    
    private bool showAnchorsField;
    
    private string tooltipClassField;
    
    public GuiTooltipDescription() {
        this.priorityField = ((float)(0F));
        this.tooltipWindowField = "";
        this.showAnchorsField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Offset FreeOffset {
        get {
            return this.freeOffsetField;
        }
        set {
            this.freeOffsetField = value;
            this.RaisePropertyChanged("FreeOffset");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Offset AnchorOffset {
        get {
            return this.anchorOffsetField;
        }
        set {
            this.anchorOffsetField = value;
            this.RaisePropertyChanged("AnchorOffset");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PanelFeatureDescription", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public GuiPanelFeatureDescription[] PanelFeatureDescription {
        get {
            return this.panelFeatureDescriptionField;
        }
        set {
            this.panelFeatureDescriptionField = value;
            this.RaisePropertyChanged("PanelFeatureDescription");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(float), "0")]
    public float Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
            this.RaisePropertyChanged("Priority");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TooltipPrefab {
        get {
            return this.tooltipPrefabField;
        }
        set {
            this.tooltipPrefabField = value;
            this.RaisePropertyChanged("TooltipPrefab");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string TooltipWindow {
        get {
            return this.tooltipWindowField;
        }
        set {
            this.tooltipWindowField = value;
            this.RaisePropertyChanged("TooltipWindow");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ShowAnchors {
        get {
            return this.showAnchorsField;
        }
        set {
            this.showAnchorsField = value;
            this.RaisePropertyChanged("ShowAnchors");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TooltipClass {
        get {
            return this.tooltipClassField;
        }
        set {
            this.tooltipClassField = value;
            this.RaisePropertyChanged("TooltipClass");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
