//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FleetNameMappingDefinition))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DatatableElement : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FleetNameAdjective))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(FleetNameTitle))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LocalizedElement : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string localizationKeyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocalizationKey {
        get {
            return this.localizationKeyField;
        }
        set {
            this.localizationKeyField = value;
            this.RaisePropertyChanged("LocalizationKey");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FleetNameAdjective : LocalizedElement {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FleetNameTitle : LocalizedElement {
    
    private FleetNameAdjective[] fleetNameAdjectiveField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FleetNameAdjective", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public FleetNameAdjective[] FleetNameAdjective {
        get {
            return this.fleetNameAdjectiveField;
        }
        set {
            this.fleetNameAdjectiveField = value;
            this.RaisePropertyChanged("FleetNameAdjective");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class FleetNameMappingDefinition : DatatableElement {
    
    private FleetNameTitle[] fleetNameTitleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FleetNameTitle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public FleetNameTitle[] FleetNameTitle {
        get {
            return this.fleetNameTitleField;
        }
        set {
            this.fleetNameTitleField = value;
            this.RaisePropertyChanged("FleetNameTitle");
        }
    }
}
