//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinigameDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExplorationMinigameDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(KingOfTheHillMinigameDefinition))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DatatableElement : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DroppableFleet))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Droppable : object, System.ComponentModel.INotifyPropertyChanged {
    
    private bool canHaveDuplicateField;
    
    private int weightField;
    
    private int maxTurnField;
    
    public Droppable() {
        this.canHaveDuplicateField = true;
        this.weightField = 1;
        this.maxTurnField = 0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool CanHaveDuplicate {
        get {
            return this.canHaveDuplicateField;
        }
        set {
            this.canHaveDuplicateField = value;
            this.RaisePropertyChanged("CanHaveDuplicate");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(1)]
    public int Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
            this.RaisePropertyChanged("Weight");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int MaxTurn {
        get {
            return this.maxTurnField;
        }
        set {
            this.maxTurnField = value;
            this.RaisePropertyChanged("MaxTurn");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DroppableFleet : Droppable {
    
    private string heroDefinitionField;
    
    private string[] shipDesignField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HeroDefinition {
        get {
            return this.heroDefinitionField;
        }
        set {
            this.heroDefinitionField = value;
            this.RaisePropertyChanged("HeroDefinition");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShipDesign", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] ShipDesign {
        get {
            return this.shipDesignField;
        }
        set {
            this.shipDesignField = value;
            this.RaisePropertyChanged("ShipDesign");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Team : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string balancingFleetCountFormulaField;
    
    private DroppableFleet[] balancingFleetField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BalancingFleetCountFormula {
        get {
            return this.balancingFleetCountFormulaField;
        }
        set {
            this.balancingFleetCountFormulaField = value;
            this.RaisePropertyChanged("BalancingFleetCountFormula");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BalancingFleet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public DroppableFleet[] BalancingFleet {
        get {
            return this.balancingFleetField;
        }
        set {
            this.balancingFleetField = value;
            this.RaisePropertyChanged("BalancingFleet");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExplorationMinigameDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(KingOfTheHillMinigameDefinition))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class MinigameDefinition : DatatableElement {
    
    private Team[] teamField;
    
    private string fleetMissionNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Team", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Team[] Team {
        get {
            return this.teamField;
        }
        set {
            this.teamField = value;
            this.RaisePropertyChanged("Team");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FleetMissionName {
        get {
            return this.fleetMissionNameField;
        }
        set {
            this.fleetMissionNameField = value;
            this.RaisePropertyChanged("FleetMissionName");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class KingOfTheHillMinigameDefinition : MinigameDefinition {
    
    private string fleetScoreFormulaField;
    
    private string guiNumberOfTurnsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FleetScoreFormula {
        get {
            return this.fleetScoreFormulaField;
        }
        set {
            this.fleetScoreFormulaField = value;
            this.RaisePropertyChanged("FleetScoreFormula");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GuiNumberOfTurns {
        get {
            return this.guiNumberOfTurnsField;
        }
        set {
            this.guiNumberOfTurnsField = value;
            this.RaisePropertyChanged("GuiNumberOfTurns");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class ExplorationMinigameDefinition : MinigameDefinition {
}
