//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(VictoryConditionDefinition))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DatatableElement : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VictoryDefinitionFormula : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InterpreterBasedVictoryConditionEvaluatorDefinition))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VictoryConditionEvaluatorDefinition : object, System.ComponentModel.INotifyPropertyChanged {
    
    private VictoryConditionAlert[] alertField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Alert", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VictoryConditionAlert[] Alert {
        get {
            return this.alertField;
        }
        set {
            this.alertField = value;
            this.RaisePropertyChanged("Alert");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class VictoryConditionAlert : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    private bool repeatField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Repeat {
        get {
            return this.repeatField;
        }
        set {
            this.repeatField = value;
            this.RaisePropertyChanged("Repeat");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InterpreterBasedVictoryConditionEvaluatorDefinition : VictoryConditionEvaluatorDefinition {
    
    private VictoryDefinitionFormula scoreFormulaField;
    
    private VictoryDefinitionFormula progressFormulaField;
    
    private VictoryDefinitionFormula discreteProgressFormulaField;
    
    private VictoryDefinitionFormula discreteObjectiveFormulaField;
    
    private string victoryExpressionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VictoryDefinitionFormula ScoreFormula {
        get {
            return this.scoreFormulaField;
        }
        set {
            this.scoreFormulaField = value;
            this.RaisePropertyChanged("ScoreFormula");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VictoryDefinitionFormula ProgressFormula {
        get {
            return this.progressFormulaField;
        }
        set {
            this.progressFormulaField = value;
            this.RaisePropertyChanged("ProgressFormula");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VictoryDefinitionFormula DiscreteProgressFormula {
        get {
            return this.discreteProgressFormulaField;
        }
        set {
            this.discreteProgressFormulaField = value;
            this.RaisePropertyChanged("DiscreteProgressFormula");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VictoryDefinitionFormula DiscreteObjectiveFormula {
        get {
            return this.discreteObjectiveFormulaField;
        }
        set {
            this.discreteObjectiveFormulaField = value;
            this.RaisePropertyChanged("DiscreteObjectiveFormula");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VictoryExpression {
        get {
            return this.victoryExpressionField;
        }
        set {
            this.victoryExpressionField = value;
            this.RaisePropertyChanged("VictoryExpression");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EmpirePerformanceTracker : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string[] variableField;
    
    private string nameField;
    
    private PerformanceType typeField;
    
    private bool hiddenField;
    
    public EmpirePerformanceTracker() {
        this.hiddenField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Variable", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] Variable {
        get {
            return this.variableField;
        }
        set {
            this.variableField = value;
            this.RaisePropertyChanged("Variable");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PerformanceType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
            this.RaisePropertyChanged("Type");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Hidden {
        get {
            return this.hiddenField;
        }
        set {
            this.hiddenField = value;
            this.RaisePropertyChanged("Hidden");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
public enum PerformanceType {
    
    /// <remarks/>
    SingleValue,
    
    /// <remarks/>
    MinMax,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class VictoryConditionDefinition : DatatableElement {
    
    private EmpirePerformanceTracker[] performanceTrackerField;
    
    private InterpreterBasedVictoryConditionEvaluatorDefinition soloEvaluatorField;
    
    private InterpreterBasedVictoryConditionEvaluatorDefinition allianceEvaluatorField;
    
    private bool activeField;
    
    private string settingNameField;
    
    private RankIndicator rankIndicatorField;
    
    private bool hiddenField;
    
    public VictoryConditionDefinition() {
        this.activeField = true;
        this.settingNameField = "True";
        this.rankIndicatorField = RankIndicator.Progress;
        this.hiddenField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PerformanceTracker", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EmpirePerformanceTracker[] PerformanceTracker {
        get {
            return this.performanceTrackerField;
        }
        set {
            this.performanceTrackerField = value;
            this.RaisePropertyChanged("PerformanceTracker");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InterpreterBasedVictoryConditionEvaluatorDefinition SoloEvaluator {
        get {
            return this.soloEvaluatorField;
        }
        set {
            this.soloEvaluatorField = value;
            this.RaisePropertyChanged("SoloEvaluator");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InterpreterBasedVictoryConditionEvaluatorDefinition AllianceEvaluator {
        get {
            return this.allianceEvaluatorField;
        }
        set {
            this.allianceEvaluatorField = value;
            this.RaisePropertyChanged("AllianceEvaluator");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
            this.RaisePropertyChanged("Active");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("True")]
    public string SettingName {
        get {
            return this.settingNameField;
        }
        set {
            this.settingNameField = value;
            this.RaisePropertyChanged("SettingName");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(RankIndicator.Progress)]
    public RankIndicator RankIndicator {
        get {
            return this.rankIndicatorField;
        }
        set {
            this.rankIndicatorField = value;
            this.RaisePropertyChanged("RankIndicator");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Hidden {
        get {
            return this.hiddenField;
        }
        set {
            this.hiddenField = value;
            this.RaisePropertyChanged("Hidden");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
public enum RankIndicator {
    
    /// <remarks/>
    Progress,
    
    /// <remarks/>
    Score,
}
